# UNet Medium Configuration: ~100-150K parameters
#
# Medium-sized 3-level U-Net with multi-scale processing
# Architecture: 256 → 128 → 64 → 128 → 256 with skip connections
# Features: 3 conv blocks per level, GELU activation
# Expected performance: 0.05-0.2% relative L2 error
#

train_dataset:
  dataset:
    name: poisson1d-synthetic
    args:
      num_samples: 10000
      resolution: 256
      freq_range: [1, 20]
      use_superposition: true
      num_components: 5
      use_float64: true
      normalize_solution: true
      seed: 42
  batch_size: 32

val_dataset:
  dataset:
    name: poisson1d-synthetic
    args:
      num_samples: 2000
      resolution: 256
      freq_range: [1, 20]
      use_superposition: true
      num_components: 5
      use_float64: true
      normalize_solution: true
      seed: 12345
  batch_size: 32

model:
  name: unet-medium
  args:
    base_channels: 32
    num_levels: 3
    kernel_size: 7
    blocks_per_level: 3
    padding_mode: reflect
    activation: gelu

optimizer:
  name: adam
  args:
    lr: 8.0e-4
    betas: [0.9, 0.999]
    weight_decay: 1.0e-6

epoch_max: 1000
epoch_val: 1
early_stopping_patience: 75

reduce_lr_on_plateau:
  mode: min
  factor: 0.5
  patience: 20
  threshold: 1.0e-9
  min_lr: 1.0e-8
  cooldown: 5
  verbose: true

grad_clip: 1.0
use_double_precision: true
loss_type: l2  # Use L2 loss instead of MSE
