# FNO-1D Configuration: ~50-80K parameters
#
# Fourier Neural Operator for 1D Poisson equation
# Architecture: 4-layer FNO with 16 modes and 64 channels
# Features: Spectral convolution in Fourier space, GELU activation
# Expected performance: 0.01-0.1% relative L2 error
#
# FNO is ideal for this problem since:
# - Sources are sinusoidal (naturally spectral)
# - Poisson equation in Fourier space: u_k = f_k / k^2
# - FNO learns this relationship directly
#

train_dataset:
  dataset:
    name: poisson1d-synthetic
    args:
      num_samples: 10000
      resolution: 256
      freq_range: [1, 20]
      use_superposition: true
      num_components: 5
      use_float64: true
      normalize_solution: true
      seed: 42
  batch_size: 32

val_dataset:
  dataset:
    name: poisson1d-synthetic
    args:
      num_samples: 2000
      resolution: 256
      freq_range: [1, 20]
      use_superposition: true
      num_components: 5
      use_float64: true
      normalize_solution: true
      seed: 12345
  batch_size: 32

model:
  name: fno-1d
  args:
    modes: 16
    width: 64
    num_layers: 4
    activation: gelu

optimizer:
  name: adam
  args:
    lr: 5.0e-4
    betas: [0.9, 0.999]
    weight_decay: 1.0e-6

epoch_max: 800
epoch_val: 1
early_stopping_patience: 60

reduce_lr_on_plateau:
  mode: min
  factor: 0.5
  patience: 15
  threshold: 1.0e-9
  min_lr: 1.0e-8
  cooldown: 5
  verbose: true

grad_clip: 1.0
use_double_precision: true
loss_type: l2  # Use L2 loss instead of MSE
